version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: resumind
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
